name: First-Workflow
on: push
jobs:
  fetch:
    name: fetch the latest code
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
