name: First-Workflow
on: push
jobs:
  fetch:
    name: fetch the latest code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  node:
    name: install node
    runs-on: ubuntu-latest
    needs: fetch
    steps:
     - uses: actions/setup-node@v3
       with:
          node-version: 18
  install:
    name: install dependencies
    runs-on: ubuntu-latest
    needs: node
    steps:
      - run: npm ci
  lint:
    name: lints the project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: npm run lint
  test:
    name: test the project
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - run: npm run test
  build:
    name: build the project
    runs-on: ubuntu-latest
    needs: test
    steps:
    - run: npm run build
